image:
  file: Dockerfile

tasks:
  - name: Fetch juice shop and run it
    before: |
      docker pull bkimminich/juice-shop
    command: |
      docker run --rm -it --env "NODE_ENV=unsafe" -p 3000:3000 bkimminich/juice-shop

ports:
  - name: juice-shop
    description: The web app juice-shop
    port: 3000
    visibility: private
    onOpen: open-preview
